import mongoose from 'mongoose';
import { MESSAGE_TYPE, MESSAGE_TYPE_VALUES, ROLE_VALUES } from '../config/constants.js';

const attachmentSchema = new mongoose.Schema(
  {
    /** Generated on the server; the file on disk is uploads/<ticketId>/<storageKey>. */
    storageKey: { type: String, required: true },
    /** Authorized API route that streams the file - never a public static URL. */
    url: { type: String, required: true },
    /** Cleaned original name, for display and download only. */
    filename: { type: String, required: true },
    mimeType: { type: String, default: '' },
    size: { type: Number, default: 0 },
  },
  { _id: false },
);

/**
 * Messages live in their own collection rather than embedded in Ticket so a
 * long conversation never bloats the ticket document (spec §23).
 */
const messageSchema = new mongoose.Schema(
  {
    ticketId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Ticket',
      required: true,
      index: true,
    },
    /** null for SYSTEM messages generated by the platform. */
    senderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
      index: true,
    },
    senderRole: {
      type: String,
      enum: [...ROLE_VALUES, 'system'],
      required: true,
    },
    type: {
      type: String,
      enum: MESSAGE_TYPE_VALUES,
      default: MESSAGE_TYPE.TEXT,
    },
    content: {
      type: String,
      // A photo can be sent on its own; a message with no photo needs text.
      required() {
        return !this.attachments?.length;
      },
      default: '',
      trim: true,
      maxlength: 4000,
    },
    attachments: { type: [attachmentSchema], default: [] },
    readBy: {
      type: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
      default: [],
    },
  },
  {
    timestamps: true,
    toJSON: {
      virtuals: true,
      transform(_doc, ret) {
        delete ret.__v;
        delete ret.id;
        return ret;
      },
    },
  },
);

// Conversation history is always read per-ticket in chronological order.
messageSchema.index({ ticketId: 1, createdAt: 1 });
messageSchema.index({ ticketId: 1, readBy: 1 });

export const Message = mongoose.model('Message', messageSchema);
